<?xml version="1.0" standalone="yes"?>
<!DOCTYPE brett [
<!ELEMENT brett (feld*)>
<!ELEMENT feld (koordinaten)>
<!ELEMENT koordinaten (x, y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ATTLIST brett name CDATA #IMPLIED>
<!ATTLIST feld nummer CDATA #REQUIRED>
]>
<brett name="prototyp">
	<feld nummer="0">
		<koordinaten>
			<x>560</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="1">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>490</x>
			<y>90</y>
		</koordinaten>
	</feld>
	<feld nummer="2">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>530</x>
			<y>90</y>
		</koordinaten>
	</feld>
	<feld nummer="3">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>490</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="4">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>530</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="5">
		<koordinaten>
			<x>500</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="6">
		<koordinaten>
			<x>470</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="7">
		<koordinaten>
			<x>440</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="8">
		<koordinaten>
			<x>410</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="9">
		<koordinaten>
			<x>530</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="10">
		<koordinaten>
			<x>500</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="11">
		<koordinaten>
			<x>470</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="12">
		<koordinaten>
			<x>440</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="13">
		<koordinaten>
			<x>420</x>
			<y>220</y>
		</koordinaten>
	</feld>
	<feld nummer="14">
		<koordinaten>
			<x>400</x>
			<y>200</y>
		</koordinaten>
	</feld>
	<feld nummer="15">
		<koordinaten>
			<x>380</x>
			<y>180</y>
		</koordinaten>
	</feld>
	<feld nummer="16">
		<koordinaten>
			<x>360</x>
			<y>160</y>
		</koordinaten>
	</feld>
	<feld nummer="17">
		<koordinaten>
			<x>360</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="18">
		<koordinaten>
			<x>360</x>
			<y>100</y>
		</koordinaten>
	</feld>
	<feld nummer="19">
		<koordinaten>
			<x>360</x>
			<y>70</y>
		</koordinaten>
	</feld>
	<feld nummer="20">
		<koordinaten>
			<x>360</x>
			<y>40</y>
		</koordinaten>
	</feld>
	<feld nummer="21">
		<koordinaten>
			<x>330</x>
			<y>40</y>
		</koordinaten>
	</feld>
	<feld nummer="22">
		<koordinaten>
			<x>300</x>
			<y>40</y>
		</koordinaten>
	</feld>
	<feld nummer="23">
		<koordinaten>
			<x>270</x>
			<y>40</y>
		</koordinaten>
	</feld>
	<feld nummer="24">
		<koordinaten>
			<x>240</x>
			<y>40</y>
		</koordinaten>
	</feld>
	<feld nummer="25">
		<typ name="lager">
		</typ>	
		<koordinaten>
			<x>70</x>
			<y>90</y>
		</koordinaten>
	</feld>
	<feld nummer="26">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>110</x>
			<y>90</y>
		</koordinaten>
	</feld>
	<feld nummer="27">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>70</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="28">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>110</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="29">
		<koordinaten>
			<x>300</x>
			<y>100</y>
		</koordinaten>
	</feld>
	<feld nummer="30">
		<koordinaten>
			<x>300</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="31">
		<koordinaten>
			<x>300</x>
			<y>160</y>
		</koordinaten>
	</feld>
	<feld nummer="32">
		<koordinaten>
			<x>300</x>
			<y>190</y>
		</koordinaten>
	</feld>
	<feld nummer="33">
		<koordinaten>
			<x>240</x>
			<y>70</y>
		</koordinaten>
	</feld>
	<feld nummer="34">
		<koordinaten>
			<x>240</x>
			<y>100</y>
		</koordinaten>
	</feld>
	<feld nummer="35">
		<koordinaten>
			<x>240</x>
			<y>130</y>
		</koordinaten>
	</feld>
	<feld nummer="36">
		<koordinaten>
			<x>240</x>
			<y>160</y>
		</koordinaten>
	</feld>
	<feld nummer="37">
		<koordinaten>
			<x>220</x>
			<y>180</y>
		</koordinaten>
	</feld>
	<feld nummer="38">
		<koordinaten>
			<x>200</x>
			<y>200</y>
		</koordinaten>
	</feld>
	<feld nummer="39">
		<koordinaten>
			<x>180</x>
			<y>220</y>
		</koordinaten>
	</feld>
	<feld nummer="40">
		<koordinaten>
			<x>160</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="41">
		<koordinaten>
			<x>130</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="42">
		<koordinaten>
			<x>100</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="43">
		<koordinaten>
			<x>70</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="44">
		<koordinaten>
			<x>40</x>
			<y>240</y>
		</koordinaten>
	</feld>
	<feld nummer="45">
		<koordinaten>
			<x>40</x>
			<y>270</y>
		</koordinaten>
	</feld>
	<feld nummer="46">
		<koordinaten>
			<x>40</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="47">
		<koordinaten>
			<x>40</x>
			<y>330</y>
		</koordinaten>
	</feld>
	<feld nummer="48">
		<koordinaten>
			<x>40</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="49">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>70</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="50">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>110</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="51">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>70</x>
			<y>510</y>
		</koordinaten>
	</feld>
	<feld nummer="52">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>110</x>
			<y>510</y>
		</koordinaten>
	</feld>
	<feld nummer="53">
		<koordinaten>
			<x>100</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="54">
		<koordinaten>
			<x>130</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="55">
		<koordinaten>
			<x>160</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="56">
		<koordinaten>
			<x>190</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="57">
		<koordinaten>
			<x>70</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="58">
		<koordinaten>
			<x>100</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="59">
		<koordinaten>
			<x>130</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="60">
		<koordinaten>
			<x>160</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="61">
		<koordinaten>
			<x>180</x>
			<y>380</y>
		</koordinaten>
	</feld>
	<feld nummer="62">
		<koordinaten>
			<x>200</x>
			<y>400</y>
		</koordinaten>
	</feld>
	<feld nummer="63">
		<koordinaten>
			<x>220</x>
			<y>420</y>
		</koordinaten>
	</feld>
	<feld nummer="64">
		<koordinaten>
			<x>240</x>
			<y>440</y>
		</koordinaten>
	</feld>
	<feld nummer="65">
		<koordinaten>
			<x>240</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="66">
		<koordinaten>
			<x>240</x>
			<y>500</y>
		</koordinaten>
	</feld>
	<feld nummer="67">
		<koordinaten>
			<x>240</x>
			<y>530</y>
		</koordinaten>
	</feld>
	<feld nummer="68">
		<koordinaten>
			<x>240</x>
			<y>560</y>
		</koordinaten>
	</feld>
	<feld nummer="69">
		<koordinaten>
			<x>270</x>
			<y>560</y>
		</koordinaten>
	</feld>
	<feld nummer="70">
		<koordinaten>
			<x>300</x>
			<y>560</y>
		</koordinaten>
	</feld>
	<feld nummer="71">
		<koordinaten>
			<x>330</x>
			<y>560</y>
		</koordinaten>
	</feld>
	<feld nummer="72">
		<koordinaten>
			<x>360</x>
			<y>560</y>
		</koordinaten>
	</feld>
	<feld nummer="73">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>490</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="74">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>530</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="75">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>490</x>
			<y>510</y>
		</koordinaten>
	</feld>
	<feld nummer="76">
		<typ name="lager">
		</typ>
		<koordinaten>
			<x>530</x>
			<y>510</y>
		</koordinaten>
	</feld>
	<feld nummer="77">
		<koordinaten>
			<x>300</x>
			<y>500</y>
		</koordinaten>
	</feld>
	<feld nummer="78">
		<koordinaten>
			<x>300</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="79">
		<koordinaten>
			<x>300</x>
			<y>440</y>
		</koordinaten>
	</feld>
	<feld nummer="80">
		<koordinaten>
			<x>300</x>
			<y>410</y>
		</koordinaten>
	</feld>
	<feld nummer="81">
		<koordinaten>
			<x>360</x>
			<y>530</y>
		</koordinaten>
	</feld>
	<feld nummer="82">
		<koordinaten>
			<x>360</x>
			<y>500</y>
		</koordinaten>
	</feld>
	<feld nummer="83">
		<koordinaten>
			<x>360</x>
			<y>470</y>
		</koordinaten>
	</feld>
	<feld nummer="84">
		<koordinaten>
			<x>360</x>
			<y>440</y>
		</koordinaten>
	</feld>
	<feld nummer="85">
		<koordinaten>
			<x>380</x>
			<y>420</y>
		</koordinaten>
	</feld>
	<feld nummer="86">
		<koordinaten>
			<x>400</x>
			<y>400</y>
		</koordinaten>
	</feld>
	<feld nummer="87">
		<koordinaten>
			<x>420</x>
			<y>380</y>
		</koordinaten>
	</feld>
	<feld nummer="88">
		<koordinaten>
			<x>440</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="89">
		<koordinaten>
			<x>470</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="90">
		<koordinaten>
			<x>500</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="91">
		<koordinaten>
			<x>530</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="92">
		<koordinaten>
			<x>560</x>
			<y>360</y>
		</koordinaten>
	</feld>
	<feld nummer="93">
		<koordinaten>
			<x>560</x>
			<y>330</y>
		</koordinaten>
	</feld>
	<feld nummer="94">
		<koordinaten>
			<x>560</x>
			<y>300</y>
		</koordinaten>
	</feld>
	<feld nummer="95">
		<koordinaten>
			<x>560</x>
			<y>270</y>
		</koordinaten>
	</feld>
	<spielerView nummer="0">
		<koordinaten>
			<x>460</x>
			<y>20</y>
		</koordinaten>
	</spielerView>
	<spielerView nummer="1">
		<koordinaten>
			<x>60</x>
			<y>20</y>
		</koordinaten>
	</spielerView>
	<spielerView nummer="2">

		<koordinaten>
			<x>60</x>
			<y>560</y>
		</koordinaten>
	</spielerView>
	<spielerView nummer="3">
		<koordinaten>
			<x>460</x>
			<y>560</y>
		</koordinaten>
	</spielerView>
	<hinweis nummer="0">
		<koordinaten>
			<x>216</x>
			<y>280</y>
		</koordinaten>
	</hinweis>
</brett>